// forge:runtime-error-bridge:v4
// Forge-owned. Auto-regenerated by forge-bootstrap if missing or unchanged.
// If you need custom client instrumentation, add it BELOW the bridge block —
// do not remove the bridge.
(() => {
  if (typeof window === "undefined") return
  // Version-scoped install guard. Using a v4-specific name guarantees v4
  // initialization is never silently skipped by an older sibling whose
  // guard variable was scoped to its own version.
  if ((window as unknown as { __forgeBridgeV4Installed?: boolean }).__forgeBridgeV4Installed) return
  ;(window as unknown as { __forgeBridgeV4Installed?: boolean }).__forgeBridgeV4Installed = true
  // eslint-disable-next-line no-console
  console.log("[forge-bridge] v4 installed (runtime errors + Next overlay scrape + screenshot + visual edits)")

  type Payload = {
    source:    "browser"
    signature?: string
    message:   string
    detail?:   string
    file?:     string
    line?:     number
    column?:   number
    stack?:    string
    url?:      string
    status?:   number
    userAgent?: string
  }

  const recent = new Map<string, number>()
  const DEDUP_MS = 2000

  // Signature inference. Without this, every error from console.error /
  // unhandledrejection / window.error gets the same generic signature
  // (console_error, unhandled_rejection, window_error), and the agent has
  // to grep the message to figure out what's actually wrong. Inferring
  // signatures up-front lets the agent (and the FE banner) branch on a
  // stable key — e.g. json_parse_error → "check what your fetch is
  // returning and confirm the route exists". Pure string sniffing, no
  // perf cost worth talking about. Order matters: most-specific first.
  const inferSignature = (msg: string, fallback: string): string => {
    const m = msg || ""
    if (/Unexpected token .* is not valid JSON|JSON\.parse|SyntaxError.*JSON/i.test(m)) return "json_parse_error"
    if (/Hydration failed|did not match.*server|Text content does not match/i.test(m)) return "hydration_mismatch"
    if (/Maximum update depth exceeded|Too many re-renders/i.test(m)) return "react_render_loop"
    if (/Cannot find module|Module not found.*resolve/i.test(m)) return "missing_module"
    if (/TypeError: Cannot read prop(?:erty|erties).* of (?:undefined|null)/i.test(m)) return "null_property_access"
    if (/ChunkLoadError|Loading chunk \d+ failed/i.test(m)) return "chunk_load_error"
    return fallback
  }

  const send = (p: Payload) => {
    // Re-tag based on the message so payloads from generic listeners get
    // a useful signature instead of "console_error" forever.
    const inferred = inferSignature(p.message, p.signature ?? "browser_error")
    p.signature = inferred
    const fp = `${p.signature ?? ""}|${p.message}|${p.file ?? ""}|${p.line ?? ""}|${p.status ?? ""}`
    const now = Date.now()
    const last = recent.get(fp) ?? 0
    if (now - last < DEDUP_MS) return
    recent.set(fp, now)
    if (recent.size > 100) {
      for (const [k, t] of recent) if (now - t > 60000) recent.delete(k)
    }
    try {
      window.parent.postMessage(
        { type: "forge:runtime-error", payload: { ...p, userAgent: navigator.userAgent } },
        "*",
      )
    } catch { /* parent unreachable — silent */ }
  }

  window.addEventListener("error", (ev) => {
    send({
      source:    "browser",
      signature: "window_error",
      message:   String(ev.message ?? "Unknown error"),
      file:      ev.filename,
      line:      ev.lineno,
      column:    ev.colno,
      stack:     ev.error?.stack,
    })
  })

  window.addEventListener("unhandledrejection", (ev) => {
    const reason = ev.reason
    send({
      source:    "browser",
      signature: "unhandled_rejection",
      message:   String(reason?.message ?? reason ?? "Unhandled promise rejection"),
      stack:     reason?.stack,
    })
  })

  const origError = console.error.bind(console)
  console.error = (...args: unknown[]) => {
    try {
      const msg = args
        .map((a) => (a instanceof Error ? a.stack ?? a.message : typeof a === "string" ? a : JSON.stringify(a)))
        .join(" ")
        .slice(0, 500)
      if (msg) {
        send({ source: "browser", signature: "console_error", message: msg })
      }
    } catch { /* never let logging break logging */ }
    origError(...args)
  }

  const origFetch = window.fetch.bind(window)
  window.fetch = async (input: RequestInfo | URL, init?: RequestInit) => {
    const res = await origFetch(input as RequestInfo, init)
    if (!res.ok) {
      const url = typeof input === "string" ? input : (input as Request).url ?? String(input)
      send({
        source:    "browser",
        signature: "fetch_not_ok",
        message:   `fetch ${url} → ${res.status}`,
        url,
        status:    res.status,
      })
    }
    return res
  }

  // ── Screenshot-on-request ─────────────────────────────────────────────────
  // Parent (Forge UI) posts { type: "forge:screenshot-request", requestId }.
  // We lazy-load html2canvas from a CDN on FIRST request — bundling it would
  // add ~45KB gzipped to every Next start across every container, even for
  // users who never click the button. On-demand keeps the cold-start tax at
  // zero. Reply with { type: "forge:screenshot-response", requestId, dataUrl }
  // or, on failure, an empty dataUrl so the parent can fall back gracefully.
  const HTML2CANVAS_CDN =
    "https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"
  let h2cPromise: Promise<unknown> | null = null
  const loadHtml2Canvas = (): Promise<unknown> => {
    const w = window as unknown as { html2canvas?: unknown }
    if (w.html2canvas) return Promise.resolve(w.html2canvas)
    if (h2cPromise) return h2cPromise
    h2cPromise = new Promise((resolve, reject) => {
      const s = document.createElement("script")
      s.src = HTML2CANVAS_CDN
      s.async = true
      s.crossOrigin = "anonymous"
      s.onload = () => {
        const fn = (window as unknown as { html2canvas?: unknown }).html2canvas
        if (fn) resolve(fn)
        else reject(new Error("html2canvas missing after load"))
      }
      s.onerror = () => reject(new Error("html2canvas CDN load failed"))
      document.head.appendChild(s)
    })
    return h2cPromise
  }

  const reply = (target: MessageEventSource | null, requestId: string, dataUrl: string) => {
    try {
      // Reply to the exact frame that asked, not "*". The parent gates the
      // response on event.origin matching the preview host pattern anyway,
      // but tighter routing here means no other listener can see the dataURL.
      ;(target as Window | null)?.postMessage(
        { type: "forge:screenshot-response", requestId, dataUrl },
        "*",
      )
    } catch { /* parent unreachable — silent */ }
  }

  window.addEventListener("message", async (ev: MessageEvent) => {
    const data = ev.data
    if (!data || typeof data !== "object") return
    if (data.type !== "forge:screenshot-request") return
    const requestId = typeof data.requestId === "string" ? data.requestId : ""
    if (!requestId) return

    try {
      const h2c = await loadHtml2Canvas() as (el: Element, opts?: unknown) => Promise<HTMLCanvasElement>
      // Cap dimensions — a 4K canvas → dataURL is ~6MB of base64, which
      // makes the parent prompt enormous and the next agent turn expensive.
      // 1280px wide is plenty for visual diagnosis at chat density.
      const MAX_W = 1280
      const scale = Math.min(1, MAX_W / Math.max(1, document.documentElement.clientWidth))
      const canvas = await h2c(document.body, {
        scale,
        useCORS:        true,
        allowTaint:     false,
        backgroundColor: "#ffffff",
        logging:        false,
      })
      // JPEG quality 0.7 — visually fine for layout debugging, ~3-4x smaller
      // than PNG. Quality knob is the right place to tune token cost later.
      const dataUrl = canvas.toDataURL("image/jpeg", 0.7)
      reply(ev.source, requestId, dataUrl)
    } catch {
      reply(ev.source, requestId, "")
    }
  })

  // ── Visual edits: select-mode ─────────────────────────────────────────────
  // Parent posts { type: "forge:select-enter" } → we attach a hover overlay
  // and a click-capture handler. On click we walk up from event.target to
  // the nearest element with data-forge-source (stamped by the source-stamp
  // loader at dev compile time) and post back:
  //   { type: "forge:select-pick", source, tag, text }
  // Esc, scroll, or `forge:select-exit` from parent ends select mode.
  //
  // Cascade safety (CLAUDE.md §3.2): the overlay is a single absolutely-
  // positioned div with INLINE styles only. We start with `all: initial` to
  // wipe every inherited property, then set the specific styles we need.
  // No class names, no global selectors, no shared CSS. The user's app
  // can't override us (max z-index, !important via setProperty priority),
  // and we can't bleed into the user's app (no shared selector surface).
  //
  // pointer-events: none on the overlay so it never swallows hover/clicks
  // — the underlying element still receives the event we listen for.
  let selectActive = false
  let selectOverlay: HTMLDivElement | null = null
  let selectLabel:   HTMLDivElement | null = null
  let selectTarget:  Element | null = null
  let selectSource:  MessageEventSource | null = null

  const overlayStyle = (el: HTMLDivElement) => {
    // Wipe inheritance, then set only what we need.
    el.style.cssText = "all: initial;"
    el.setAttribute("data-forge-overlay", "1")
    // setProperty with "important" beats any !important rule the user's
    // app might inject via a wildcard selector.
    const set = (k: string, v: string) => el.style.setProperty(k, v, "important")
    set("position",        "fixed")
    set("pointer-events",  "none")
    set("z-index",         "2147483647")
    set("border",          "2px solid #4f8cff")
    set("background",      "rgba(79, 140, 255, 0.12)")
    set("box-shadow",      "0 0 0 1px rgba(255, 255, 255, 0.6) inset")
    set("transition",      "all 80ms ease-out")
    set("box-sizing",      "border-box")
    set("display",         "none")
  }

  // Small tag-name pill anchored above the highlighted element. Same
  // cascade-safety treatment as the outline overlay (all: initial, inline
  // !important, unique data attribute, pointer-events: none).
  const labelStyle = (el: HTMLDivElement) => {
    el.style.cssText = "all: initial;"
    el.setAttribute("data-forge-overlay-label", "1")
    const set = (k: string, v: string) => el.style.setProperty(k, v, "important")
    set("position",        "fixed")
    set("pointer-events",  "none")
    set("z-index",         "2147483647")
    set("background",      "#4f8cff")
    set("color",           "#ffffff")
    set("font",            "600 11px/1 -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif")
    set("padding",         "3px 6px")
    set("border-radius",   "3px 3px 0 0")
    set("white-space",     "nowrap")
    set("display",         "none")
  }

  const ensureOverlay = (): HTMLDivElement => {
    if (selectOverlay && selectOverlay.isConnected) return selectOverlay
    const el = document.createElement("div")
    overlayStyle(el)
    document.documentElement.appendChild(el)
    selectOverlay = el
    return el
  }

  const ensureLabel = (): HTMLDivElement => {
    if (selectLabel && selectLabel.isConnected) return selectLabel
    const el = document.createElement("div")
    labelStyle(el)
    document.documentElement.appendChild(el)
    selectLabel = el
    return el
  }

  const positionOverlay = (target: Element | null) => {
    const ov = selectOverlay
    const lb = selectLabel
    if (!ov || !lb) return
    if (!target) {
      ov.style.setProperty("display", "none", "important")
      lb.style.setProperty("display", "none", "important")
      return
    }
    const r = target.getBoundingClientRect()
    if (r.width === 0 && r.height === 0) {
      ov.style.setProperty("display", "none", "important")
      lb.style.setProperty("display", "none", "important")
      return
    }
    ov.style.setProperty("display", "block", "important")
    ov.style.setProperty("top",    r.top + "px",    "important")
    ov.style.setProperty("left",   r.left + "px",   "important")
    ov.style.setProperty("width",  r.width + "px",  "important")
    ov.style.setProperty("height", r.height + "px", "important")

    // Label content: <tag> + truncated text snippet. Cheap textContent
    // read — no innerHTML, no XSS surface.
    const tag = (target.tagName || "").toLowerCase()
    const text = (target.textContent || "").trim().replace(/\s+/g, " ").slice(0, 40)
    lb.textContent = text ? `<${tag}>  ${text}` : `<${tag}>`

    // Label sits above the box; if the box is too close to the top of the
    // viewport, flip it inside the top edge so it stays visible.
    lb.style.setProperty("display", "block", "important")
    const labelH = 18 // approx, matches font + padding
    const labelTop = r.top - labelH < 2 ? r.top + 2 : r.top - labelH
    lb.style.setProperty("top",  labelTop + "px", "important")
    lb.style.setProperty("left", r.left + "px",   "important")
  }

  // Walk up from `start` to the nearest ancestor with data-forge-source,
  // OR the element itself if it has it. Returns null if none — caller
  // falls back to the clicked element directly.
  const findStamped = (start: Element | null): Element | null => {
    let cur: Element | null = start
    let hops = 0
    while (cur && hops < 12) {
      if (cur.hasAttribute && cur.hasAttribute("data-forge-source")) return cur
      cur = cur.parentElement
      hops++
    }
    return null
  }

  const onMove = (ev: MouseEvent) => {
    if (!selectActive) return
    const target = ev.target as Element | null
    // Don't highlight the overlay itself.
    if (!target || target === selectOverlay) return
    selectTarget = target
    positionOverlay(target)
  }

  const onClick = (ev: MouseEvent) => {
    if (!selectActive) return
    // Capture-phase: stop the app from receiving this click. We must use
    // stopImmediatePropagation because the user's app may have its own
    // capture-phase listeners; plain stopPropagation isn't enough.
    ev.preventDefault()
    ev.stopImmediatePropagation()

    const clicked = ev.target as Element | null
    const target  = clicked && clicked !== selectOverlay ? clicked : selectTarget
    const stamped = findStamped(target)
    const picked  = stamped ?? target
    const source  = stamped?.getAttribute("data-forge-source") ?? null
    const tag     = (picked?.tagName ?? "").toLowerCase()
    const text    = (picked?.textContent ?? "").trim().replace(/\s+/g, " ").slice(0, 80)

    try {
      ;(selectSource as Window | null)?.postMessage(
        { type: "forge:select-pick", source, tag, text },
        "*",
      )
    } catch { /* parent unreachable — silent */ }

    exitSelect()
  }

  const onKey = (ev: KeyboardEvent) => {
    if (!selectActive) return
    if (ev.key === "Escape") {
      ev.preventDefault()
      try {
        ;(selectSource as Window | null)?.postMessage({ type: "forge:select-cancelled" }, "*")
      } catch { /* silent */ }
      exitSelect()
    }
  }

  const enterSelect = (src: MessageEventSource | null) => {
    if (selectActive) { selectSource = src; return }
    selectActive = true
    selectSource = src
    ensureOverlay()
    ensureLabel()
    // Capture phase so we beat the app's own handlers to the click.
    document.addEventListener("mousemove", onMove,  true)
    document.addEventListener("click",     onClick, true)
    document.addEventListener("keydown",   onKey,   true)
    // Crosshair cursor signals select mode without injecting a CSS class
    // that could collide with the user's styles.
    document.documentElement.style.setProperty("cursor", "crosshair", "important")
    // eslint-disable-next-line no-console
    console.log("[forge-bridge] select-mode ENTERED")
  }

  const exitSelect = () => {
    if (!selectActive) return
    selectActive = false
    selectTarget = null
    document.removeEventListener("mousemove", onMove,  true)
    document.removeEventListener("click",     onClick, true)
    document.removeEventListener("keydown",   onKey,   true)
    document.documentElement.style.removeProperty("cursor")
    if (selectOverlay) selectOverlay.style.setProperty("display", "none", "important")
    if (selectLabel)   selectLabel.style.setProperty("display", "none", "important")
    // eslint-disable-next-line no-console
    console.log("[forge-bridge] select-mode EXITED")
  }

  window.addEventListener("message", (ev: MessageEvent) => {
    const data = ev.data
    if (!data || typeof data !== "object") return
    if (data.type === "forge:select-enter") {
      enterSelect(ev.source)
    } else if (data.type === "forge:select-exit") {
      exitSelect()
    }
  })

  // ── Next.js dev-overlay scraper ───────────────────────────────────────────
  // Why this exists: Next 15 + Turbopack intercepts many runtime errors and
  // renders them in the Console/Build overlay BEFORE our console.error shim
  // runs (the overlay's wrapper runs at module-init time). For those errors
  // the bridge would otherwise never fire — exactly the failure mode the
  // user keeps hitting ("Forge isn't picking this up"). We watch the
  // <nextjs-portal> element Next mounts for the overlay, scrape the visible
  // error text out of its shadow root on mutation, and post it like any
  // other browser error. Dedup is the same map send() already uses, so a
  // single error that's also shown in console + overlay only ships once.
  //
  // Cost shape: one MutationObserver scoped to document.body, only on
  // childList. Re-scopes to the portal's shadowRoot the moment the portal
  // appears — much cheaper than polling. No work at all when there's no
  // error overlay rendered.
  const scrapeOverlay = (root: ParentNode): void => {
    // Next.js dialog selectors. They have changed across major versions;
    // we try the v13/v14/v15 shapes in order. First non-empty wins.
    const sels = [
      "[data-nextjs-dialog-body]",
      "[data-nextjs-dialog]",
      "[data-nextjs-toast-errors-parent]",
      ".nextjs-container-errors-body",
      ".nextjs-container-errors-header",
      "nextjs-portal",
    ]
    for (const sel of sels) {
      const el = root.querySelector(sel)
      if (!el) continue
      // textContent strips style; we only want the human-readable error.
      const text = (el.textContent || "").trim().slice(0, 600)
      if (!text || text.length < 6) continue
      send({
        source:    "browser",
        signature: "next_overlay_error",
        message:   text,
      })
      return
    }
  }

  const attachOverlayObserver = (): void => {
    // Find the portal lazily. Next mounts it the first time it has anything
    // to show; before that, document.body is the right level to watch.
    let portalRoot: ShadowRoot | null = null
    const tryAttachPortal = (): boolean => {
      const portal = document.querySelector("nextjs-portal")
      if (!portal || !(portal as HTMLElement).shadowRoot) return false
      portalRoot = (portal as HTMLElement).shadowRoot
      const inner = new MutationObserver(() => {
        if (portalRoot) scrapeOverlay(portalRoot)
      })
      inner.observe(portalRoot, { childList: true, subtree: true, characterData: true })
      // Initial scrape — overlay may already be rendered when we attach.
      scrapeOverlay(portalRoot)
      return true
    }
    if (tryAttachPortal()) return
    const outer = new MutationObserver(() => {
      if (tryAttachPortal()) outer.disconnect()
    })
    outer.observe(document.body, { childList: true, subtree: false })
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", attachOverlayObserver, { once: true })
  } else {
    attachOverlayObserver()
  }
})()

export {}
